try:
    import test
except Exception:
    print("Problem")
    exit(1)

print("good")